# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Deborah Digges
tagline:          'A Technical blog'
description:      'Blog entries'
url:              http://deborah-digges.github.io
baseurl:          '/'
paginate:         5

author:
  name:           ''
  url:            

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
