# Dependencies
rouge:         true

# Permalinks
permalink:        pretty

# Setup
title:            Deborah Digges
tagline:          'A Technical blog'
description:      'Blog entries'
excerpt_separator: ''
url:              http://deborah-digges.github.io
baseurl:          '/'
paginate:         10

author:
  name:           ''
  url:            

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon

gems: [jekyll-crosspost-to-medium]