# Setup
title:            Deborah Digges
tagline:          'A Technical blog'

description:      ''
url:
baseurl:          '/'
paginate:         5
permalink:           pretty

# About/contact
author:
  name:          Deborah Digges
  url:           https://twitter.com/DeborahDigges12
  email:         deborah.gertrude.digges@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
