# Setup
title:            Deborah Digges
tagline:          'A Technical blog'
description:      'Blog entries'
excerpt_separator: ''
url:              http://deborah-digges.github.io
baseurl:          '/'
permalink:           pretty
paginate:         10

# About/contact
author:
  name:          Deborah Digges
  url:           https://twitter.com/DeborahDigges12
  email:         deborah.gertrude.digges@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
github:
  repo:           https://github.com/poole/lanyon
gems: [jekyll-crosspost-to-medium]
